import 'package:flutter/material.dart';

class Committee extends StatefulWidget {
  const Committee({super.key});

  @override
  State<Committee> createState() => _CommitteeState();
}

class _CommitteeState extends State<Committee> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Organising Committee"),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
                padding: const EdgeInsets.only(top: 10,bottom: 15),
                child: const Center(child:Text("Organising Committee",style: TextStyle(fontSize: 25,fontWeight: FontWeight.bold),),
              ),
            ),
            const Text("Chief Patron:",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Sarojini Agarwal, Chairperson NIET- G. Noida"),
            const Text("Dr. Om Prakash Agarwal,Managing Director,"),
            const Text("NIET-G. Noida"),
            const SizedBox(height:10,),
            const Text("Patrons:",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Neema Agarwal,Additional Managing Director,"),
            const Text("NIET-G. Noida"),
            const Text("Dr. Raman Batra, Executive Vice President,"),
            const Text("NIET-G. Noida"),
            const SizedBox(height: 10,),
            const Text("General Chair:",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Vinod M Kapse, Director, NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("Convener:",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Priyanka Chandani, HoD, AI-DS-CSBS,"),
            const Text("NIET-G. Noida"),
            const SizedBox(height: 10,),
            const Text("Co-Convener",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Mohammad Shahid, HoD, AIML,"),
            const Text("NIET-G. Noida"),
            const Text("Mr. Mayank Deep Khare, HoD, IOT,"),
            const Text("NIET-G. Noida"),
            const Text("Ms Bhawna Wadhwa, HoD, CS, "),
            const Text(" NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("Organizing Chairs:",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. D.R. Somashekhar, Dean Admin, NIET- G. Noida"),
            const Text("Dr. C S Yadav, Dean MCA, NIET-G. Noida"),
            const Text("Dr. Kumud Saxena, HoD CSE/IT, NIET-G. Noida"),
            const Text("Dr. Rashmi Mishra, HoD, BT, NIET-G. Noida"),
            const Text("Dr. Pawan Kumar Shukla, HoD ECE, NIET-G. Noida"),
            const Text("Dr. Sonia Munjal, HoD, MBA, NIET -G. Noida"),
            const Text("Dr. Apoorva Joshi, HoD, MCA, NIET-G. Noida "),
            const Text("Dr. Ghazala Naaz, HoD, English, NIET-G. Noida"),
            const SizedBox(height: 10,),
            const Text("Industry Chair: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Sushil Parashar, Dean Placements, NIET-G. Noida"),
            const Text("Mr. Ajeet Kunwar Singh, Head-CMC, NIET-G. Noida"),
            const SizedBox(height: 10,),
            const Text("Editorial Board: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Ms. Amita Shukla, A.P. CSBS, NIET-Greater Noida"),
            const Text("Ms. Aarushi Thusu, A.P. AIML NIET-Greater Noida"),
            const Text("Ms. Garima Dhawan, A.P. DS NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("Technical Review Committee: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Mr. Utsav Malviya, Dy HoD, IoT, NIET-Greater Noida"),
            const Text("Ms. Roshan Jameel, A.P. AI, NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("Session Coordination Committee: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Ms. Garima Jain, Dy HoD, CSBS, NIET-Greater Noida"),
            const Text("Mr. Vivek Ranjan, A.P. CS, NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("International Coordination Committee: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Ms Anjali Sharma,Inter. Outreach & Partnerships"),
            const Text(" NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("Registration Committee: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Vikas Sagar, Dy HoD, AI, NIET-Greater Noida"),
            const Text("Ms. Nishu Niharika, A.P. CS, NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("Media Committee: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Mr. Sovers Singh Bisht, Dy HoD, DS, NIET-G. Noida"),
            const Text("Mr. Raju, A.P. DS, NIET-Greater Noida"),
            const Text("Ms. Vatika Jalali, A.P. IOT, NIET-Greater Noida"),
            const Text("Ms. Nisha Verma, A.P. DS, NIET-Greater Noida"),
            const SizedBox(height: 10,),
            const Text("Hospitality & Welcome Committee: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Ms. Alisha Sikri, Dy HoD, AIML, NIET-G. Noida"),
            const Text("Mr. Amarpal Yadav, A.P. AI, NIET-G. Noida"),
            const Text("Ms. Sonia Arora, A.P.  DS, NIET-G. Noida"),
            const Text("Ms. Ayushi Pandey, A.P. CSBS, NIET-G. Noida"),
            const Text("Mr. Amit Yadav, DGM, Placement Cell, NIET-G. Noida"),
            const Text("Ms Anita Menon, Manager-CMS, NIET-G. Noida"),
            const SizedBox(height: 10,),
            const Text("Event Coordination Committee: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Manish Kaushik,DSW, NIET-G. Noida"),
            const Text("Dr. Shuchi Sethi, HoD, Cyber Security, NIET-G. Noida"),
            const Text("Mr. Harsh Awasthi, A.P. MBA, NIET-G. Noida"),
            const Text("Ms. Kanika Jindal, A.P. ECE, NIET-G. Noida"),
            const SizedBox(height: 10,),
            const Text("Finance and Accounting: ",style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold),),
            const SizedBox(height: 3,),
            const Text("Dr. Kumod Gupta, A.P. AI, NIET-Greater Noida"),
            const Text("Mr. Sanjeev Gupta,FO , NIET-Greater Noida"),
            const SizedBox(height: 10,),
          ],
        ),
      ),
    );
  }
}
